class_path_web/core/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('', views.home, name='home'),
    path('dashboard/', views.dashboard, name='dashboard'),
]

class_path_web/location/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('create-location/', views.create_location, name='create-location'),
    path('update-location/<int:pk>/', views.update_location, name='update-location'),
    path('delete-location/<int:pk>/', views.delete_location, name='delete-location'),
    path('list-location/', views.list_location, name='list-location'),
]

class_path_web/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include 


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('class_path_web.core.urls', 'core'), namespace="core")),
    path(
        'accounts/',
        include(
            ('class_path_web.accounts.urls', 'accounts'),
            namespace="accounts"
        )
    ),
    path(
        'location/',
        include(
            ('class_path_web.location.urls', 'location'),
            namespace="location"
        )
    ),
    path(
        'content/',
        include(
            ('class_path_web.content.urls', 'content'),
            namespace="content"
        )
    )
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

class_path_web/location/models.py
from django.db import models

from ..accounts.models import Teacher


class Location(models.Model):
    name = models.CharField(max_length=250)
    teacher = models.ForeignKey(
        Teacher,
        on_delete=models.CASCADE,
        related_name="locations"
    )
    description = models.TextField(blank=True, null=True)
    latitude = models.FloatField()
    longitude = models.FloatField()
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)
 
    class Meta:
        db_table = 'location'

    def __str__(self):
        return f'{self.name}: {self.latitude}, {self.longitude}'

class_path_web/location/forms.py
from django.forms import ModelForm

from . import models

class LocationForm(ModelForm):
    class Meta:
        model = models.Location
        fields = (
            'name', 'description', 'latitude',
            'longitude'
        )

class_path_web/location/views.py
from django.contrib.auth.decorators import login_required, permission_required
from django.views import generic
from django.urls import reverse_lazy as r
from django.utils.decorators import method_decorator

from ..core import base_views as base_core_views
from . import base_views, forms, models


@method_decorator(login_required, name='dispatch')
@method_decorator(permission_required('accounts.is_teacher'), name='dispatch')
class CreateLocationView(base_core_views.BaseFormView, generic.CreateView):
    form_class = forms.LocationForm
    template_title = 'Criar Localização'
    success_url = r('location:list-location')
    template_name = 'location/location_form.html'

    def form_valid(self, form):
        location = form.save(commit=False)
        location.teacher = self.request.user.teacher
        self.object = location.save()
        return super().form_valid(form)


@method_decorator(login_required, name='dispatch')
@method_decorator(permission_required('accounts.is_teacher'), name='dispatch')
class UpdateLocationView(
    base_views.LocationBaseQueryset,
    base_core_views.BaseFormView,
    generic.UpdateView):
    form_class = forms.LocationForm
    success_url = r('location:list-location')
    template_title = 'Editar Localização'
    template_name = 'location/location_form.html'
    context_object_name = 'location'


@method_decorator(login_required, name='dispatch')
@method_decorator(permission_required('accounts.is_teacher'), name='dispatch')
class ListLocationView(base_views.LocationBaseQueryset, generic.ListView):
    context_object_name = 'locations'
    template_name = 'location/location_list.html'


@method_decorator(login_required, name='dispatch')
@method_decorator(permission_required('accounts.is_teacher'), name='dispatch')
class DeleteLocationView(
    base_views.LocationBaseQueryset,
    base_core_views.BaseDelete):

    success_url = r('location:list-location')

create_location = CreateLocationView.as_view()
update_location = UpdateLocationView.as_view()
delete_location = DeleteLocationView.as_view()
list_location = ListLocationView.as_view()

frontend/templates/location/location_form.html
{% extends 'dashboard_base.html' %}
{% load staticfiles %}

{% block title %} {{ template_title }} {% endblock title %}

{% block extra_styles %}
    <link href="{% static 'styles/form.css' %}" rel="stylesheet">
{% endblock extra_styles %}

{% block content %}
<h1 class="h3 mb-2 text-gray-800">{{ template_title }}</h1>
<p class="mb-4">A partir de uma localização é possivel criar conteúdos geolocalizados.</p>
<div class="col-xl-10 col-lg-10">
    <div class="card shadow mb-4 border-left-primary">
        <div class="card-body">
            <form action="" method="POST">
                {% csrf_token %}
                <div class="form-group">
                {% include 'form_field.html' with field=form.name label=form.name.label %}
                </div>
                <div class="form-group">
                    {% include 'form_field.html' with field=form.description label=form.description.label %}
                </div>
                <div class="form-group row">
                    <div class="col-sm-6 mb-3 mb-sm-0">
                        {% include 'form_field.html' with field=form.latitude label=form.latitude.label %}
                    </div>
                    <div class="col-sm-6">
                        {% include 'form_field.html' with field=form.longitude label=form.longitude.label %}
                    </div>
                </div>
                <div class="col-xl-2 float-right">
                    <button class="btn btn-primary btn-user btn-block" type="submit">Salvar</button>
                </div>
                <div class="col-xl-2 float-right">
                    <a href="{% url 'location:list-location' %}" class="btn btn-secondary btn-user btn-block">
                        Voltar
                    </a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

frontend/templates/location/location_list.html
{% extends 'dashboard_base.html' %}
{% load static %}

{% block title %} Localizações {% endblock title %}

{% block extra_styles %}
    <link href="{% static 'styles/list.css' %}" rel="stylesheet">
{% endblock extra_styles %}


{% block content %}
    <h1 class="h1 mb-2 text-gray-800">Localizações</h1>
    <p class="mb-4">
        <a href="{% url 'location:create-location' %}">
            <i class="fas fa-plus-circle"></i>
            Clique aqui para adicionar
        </a><br>
        <a href="{% url 'core:dashboard' %}">
            <i class="fas fa-arrow-circle-left"></i>
            Voltar a pagina inicial
        </a>
    </p>

    <div class="card shadow mb-4">
      <div class="card-body">
        <div class="table-responsive">
          <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
            <thead>
              <tr>
                <th>Nome</th>
                <th>Ações</th>
              </tr>
            </thead>
            <tbody>
              {% for location in locations %}
                <tr>
                    <td><span class="font-weight-bold" data-location-id="{{ location.id }}">{{ location.name }}</span></td>
                    <td>
                        <a href="{% url 'location:update-location' pk=location.id %}" class="btn btn-edit btn-warning btn-circle"
                          data-toggle="tooltip" data-placement="right" title="Editar Localização">
                          <i class="fas fa-edit"></i>
                        </a>
                        <a href="{% url 'location:delete-location' pk=location.id %}" class="btn btn-danger btn-circle"
                          data-toggle="tooltip" data-placement="right" title="Excluir Localização">
                          <i class="fas fa-trash"></i>
                        </a>
                    </td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
{% endblock content %}

{% block extra_scripts %}
  <script src="{% static 'theme/vendor/datatables/jquery.dataTables.min.js' %}"></script>
  <script src="{% static 'theme/vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>
  <script src="{% static 'js/list.js' %}"></script>
{% endblock extra_scripts %}