class_path_web/accounts/api/urls.py
from django.urls import path

from . import viewsets


urlpatterns = [
    path('program-informations', viewsets.program_informations, name='program-informations'),
    path('class-informations', viewsets.class_informations, name='class-informations'),
]

class_path_web/accounts/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views

from . import views


urlpatterns = [
    path('api/', include(('class_path_web.accounts.api.urls', 'core'), namespace="core")),
    path('sign-up/', views.signup, name='sign-up'),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    path(
        'login/',
        auth_views.LoginView.as_view(
            template_name='accounts/login.html',
            redirect_authenticated_user=True
        ),
        name="login"
    ),
    # create
    path('create-program/', views.create_program, name='create-program'),
    path('create-teacher/', views.create_teacher, name='create-teacher'),
    path('create-class/<int:program>/', views.create_class, name='create-class'),
    path('create-student/<int:class>/', views.create_student, name='create-student'),
    path('create-course/<int:class>/', views.create_course, name='create-course'),
    path('create-address/', views.create_address, name='create_address'),
    # update
    path('update-program/<int:pk>/', views.update_program, name='update-program'),
    path('update-teacher/<int:pk>/', views.update_teacher, name='update-teacher'),
    path('update_class/<int:pk>/', views.update_class, name='update-class'),
    path('update-student/<int:pk>/', views.update_student, name='update-student'),
    path('update-course/<int:pk>/', views.update_course, name='update-course'),
    path('update-profile/', views.update_profile, name='update_profile'),
    path('update-address/<int:pk>/', views.update_address, name='update_address'),
    path(
        'define-scores/<int:student>/<int:course>/',
        views.define_scores,
        name='define-scores'
    ),
    # list
    path('programs/', views.list_program, name='list-program'),
    path('teachers/', views.list_teacher, name='list-teacher'),
    path('teacher-courses/', views.list_teacher_courses, name='list-teacher-courses'),
    path('classes/<int:program>/', views.list_class, name='list-class'),
    path('class/<int:course>/', views.list_class_students, name='list-class-students'),
    path('students/<int:class>/', views.list_student, name='list-student'),
    path('courses/<int:class>/', views.list_course, name='list-course'),
    # delete
    path('delete-program/<int:pk>/', views.delete_program, name='delete-program'),
    path('delete-class/<int:pk>/', views.delete_class, name='delete-class'),
    path('delete-teacher/<int:pk>/', views.delete_teacher, name='delete-teacher'),
    path('delete-student/<int:pk>/', views.delete_student, name='delete-student'),
    path('delete-course/<int:pk>/', views.delete_course, name='delete-course'),
    path('delete-address/<int:pk>/', views.delete_address, name='delete-address'),
    # detail
    path('profile/', views.profile_view, name='profile'),
    # has no institution urls
    path('teacher/sign-up/', views.sign_up_teacher, name='teacher-sign-up'),
    path('teacher/create-class/', views.create_teacher_class, name="teacher-create-class"),
    path('teacher/classes/', views.teacher_classes, name='teacher-classes'),
]

class_path_web/core/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('', views.home, name='home'),
    path('dashboard/', views.dashboard, name='dashboard'),
]

class_path_web/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include 


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('class_path_web.core.urls', 'core'), namespace="core")),
    path(
        'accounts/',
        include(
            ('class_path_web.accounts.urls', 'accounts'),
            namespace="accounts"
        )
    ),
    path(
        'location/',
        include(
            ('class_path_web.location.urls', 'location'),
            namespace="location"
        )
    ),
    path(
        'content/',
        include(
            ('class_path_web.content.urls', 'content'),
            namespace="content"
        )
    )
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

class_path_web/accounts/models.py
from django.contrib.auth.models import AbstractUser, Permission
from django.contrib.contenttypes.models import ContentType

from django.db import models

from django.utils.translation import gettext_lazy as _

from .managers import CustomUserManager


class User(AbstractUser):
    registration_number = models.CharField(
        _('registration number'),
        max_length=25,
        unique=True
    )
    email = models.EmailField(_('email address'), unique=True)
    is_teacher = models.BooleanField(_('is teacher'), default=False)
    is_student = models.BooleanField(_('is student'), default=False)
    is_admin = models.BooleanField(_('is admin'), default=False)
    has_institution = models.BooleanField(_('has institution'), default=True)

    objects = CustomUserManager()

    username = None

    USERNAME_FIELD = 'registration_number'

    class Meta:
        db_table = 'users'

    def __str__(self):
        return self.email


class Profile(models.Model):
    cpf = models.CharField(
        _('cpf'),
        max_length=100,
        default=None,
        null=True,
        blank=True
    )
    description = models.TextField(_('description'), blank=True, null=True)
    is_active = models.BooleanField(_('is active'), default=True)
    created_at = models.DateTimeField(_('created at'), auto_now_add=True)
    modified_at = models.DateTimeField(_('modified at'), auto_now=True)

    class Meta:
        abstract = True

    def __str__(self):
        return self.user.email


class Institution(models.Model):
    name = models.CharField(_('name'), max_length=250)
    description = models.TextField(_('description'), blank=True, null=True)
    created_at = models.DateTimeField(_('created at'), auto_now_add=True)
    modified_at = models.DateTimeField(_('modified at'), auto_now=True)

    class Meta:
        db_table = 'institution'

    def __str__(self):
        return self.name


class Program(models.Model):
    name = models.CharField(_('name'), max_length=200)
    description = models.TextField(_('description'), blank=True, null=True)
    institution = models.ForeignKey(
        Institution,
        related_name="programs",
        on_delete=models.CASCADE
    )
    created_at = models.DateTimeField(_('created at'), auto_now_add=True)
    modified_at = models.DateTimeField(_('modified at'), auto_now=True)

    class Meta:
        db_table = 'program'

    def __str__(self):
        return self.name


class Teacher(Profile):
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        related_name="teacher"
    )
    institution = models.ForeignKey(
        Institution,
        on_delete=models.CASCADE,
        related_name="teachers",
        null=True,
    )
    created_at = models.DateTimeField(_('created at'), auto_now_add=True)
    modified_at = models.DateTimeField(_('modified at'), auto_now=True)

    class Meta:
        db_table = 'teacher'


class Class(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(blank=True, null=True)
    program = models.ForeignKey(
        Program,
        on_delete=models.CASCADE,
        related_name="classes",
        null=True
    )
    teacher = models.ForeignKey(
        Teacher,
        on_delete=models.CASCADE,
        related_name="classes",
        null=True
    )
    created_at = models.DateTimeField(_('created at'), auto_now_add=True)
    modified_at = models.DateTimeField(_('modified at'), auto_now=True)

    class Meta:
        db_table = 'class'

    def __str__(self):
        return self.name


class Admin(Profile):
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        related_name="admin"
    )
    institution = models.ForeignKey(
        Institution,
        on_delete=models.CASCADE,
        related_name="admins",
        null=True,
    )
    created_at = models.DateTimeField(_('created at'), auto_now_add=True)
    modified_at = models.DateTimeField(_('modified at'), auto_now=True)

    class Meta:
        db_table = 'admin'


class Student(Profile):
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        related_name="student"
    )
    class_id = models.ForeignKey(
        Class,
        on_delete=models.CASCADE,
        related_name="students"
    )
    created_at = models.DateTimeField(_('created at'), auto_now_add=True)
    modified_at = models.DateTimeField(_('modified at'), auto_now=True)

    class Meta:
        db_table = 'student'


class Address(models.Model):
    state = models.CharField(_('state'), max_length=2)
    city = models.CharField(_('city'), max_length=100)
    street = models.CharField(_('street'), max_length=250)
    neighborhood = models.CharField(_('neighborhood'), max_length=100)
    number = models.IntegerField(_('number'), null=True)
    postal_code = models.CharField(_('postal code'), max_length=250)
    complement = models.CharField(
        _('complement'),
        max_length=250,
        blank=True,
        null=True
    )
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='addresses'
    )
    created_at = models.DateTimeField(_('created at'), auto_now_add=True)
    modified_at = models.DateTimeField(_('modified at'), auto_now=True)

    class Meta:
        db_table = 'address'

    def __str__(self):
       return f'{self.street} {self.number}, {self.postal_code}'


class Course(models.Model):
    name = models.CharField(_('name'), max_length=200)
    description = models.TextField(_('description'), blank=True, null=True)
    class_id = models.ForeignKey(
        Class,
        on_delete=models.CASCADE,
        related_name="courses"
    )
    teacher = models.ForeignKey(
        Teacher,
        on_delete=models.CASCADE,
        related_name="courses"
    )
    created_at = models.DateTimeField(_('created at'), auto_now_add=True)
    modified_at = models.DateTimeField(_('modified at'), auto_now=True)

    class Meta:
        db_table = 'course'

    def __str__(self):
        return self.name


class Scores(models.Model):
    first_score = models.FloatField(_('first score'), null=True)
    second_score = models.FloatField(_('second score'), null=True)
    third_score = models.FloatField(_('third score'), null=True)
    student = models.ForeignKey(
        Student,
        on_delete=models.CASCADE,
        related_name="scores"
    )
    course = models.ForeignKey(
        Course,
        on_delete=models.CASCADE,
        related_name="scores"
    )
    created_at = models.DateTimeField(_('created at'), auto_now_add=True)
    modified_at = models.DateTimeField(_('modified at'), auto_now=True)

    class Meta:
        db_table = 'scores'

    def __str__(self):
        return self.name

class_path_web/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm

from . import models


class InstitutionForm(ModelForm):
    class Meta:
        model = models.Institution
        fields = (
            'name', 'description',
        )


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = models.User
        fields = (
            "registration_number", "email",
            "first_name", "last_name",
        )

    def process_cleaned_data(self):
        data = self.cleaned_data.copy()

        del data['password2']

        data['password'] = data.pop('password1')
        return data

    def save(self):
        # define user permission field
        data = self.process_cleaned_data()
        # create user
        user = models.User.objects.create_user(**data)
        return user


class CustomUserUpdateForm(ModelForm):
    class Meta:
        model = models.User
        fields = (
            "registration_number", "email",
            "first_name", "last_name",
        )


class ProfileForm(ModelForm):
    class Meta:
        model = models.Teacher
        fields = (
            'cpf', 'description',
        )


class AddressForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['number'].required = False

    class Meta:
        model = models.Address
        fields = (
            'state', 'city', 'street',
            'neighborhood', 'number',
            'postal_code', 'complement'
        )


class ProgramForm(ModelForm):
    class Meta:
        model = models.Program
        fields = (
            'name', 'description'
        )


class ClassForm(ModelForm):
    class Meta:
        model = models.Class
        fields = (
            'name', 'description'
        )


class CourseForm(ModelForm):
    class Meta:
        model = models.Course
        fields = (
            'name', 'description',
            'teacher'
        )


class ScoreForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['first_score'].required = False
        self.fields['second_score'].required = False
        self.fields['third_score'].required = False

    class Meta:
        model = models.Scores
        fields = (
            'first_score', 'second_score',
            'third_score',
        )

frontend/templates/accounts/teacher/teacher_form.html
{% extends 'dashboard_base.html' %}
{% load staticfiles %}

{% block title %} {{ template_title }} {% endblock title %}

{% block extra_styles %}
    <link href="{% static 'styles/form.css' %}" rel="stylesheet">
{% endblock extra_styles %}

{% block content %}
<h1 class="h3 mb-2 text-gray-800">{{ template_title }}</h1>
<p class="mb-4">O professor é resposável por ministrar uma ou mais disciplinas, criar conteúdos e aplicar atividades.</p>
<div class="col-xl-10 col-lg-10">
    <div class="card shadow mb-4 border-left-primary">
        <div class="card-body">
            <form action="" method="POST">

              {% csrf_token %}

              {% if teacher_form %}
                <!-- available only in update view -->
                <div class="form-group">
                  {% include 'form_field.html' with field=teacher_form.cpf label=teacher_form.cpf.label %}
                </div>
                <div class="form-group">
                  {% include 'form_field.html' with field=teacher_form.description label=teacher_form.description.label %}
                </div>
              {% endif %}

              <div class="form-group row">
                <div class="col-sm-6 mb-3 mb-sm-0">
                  {% include 'form_field.html' with field=form.registration_number label="Username / Registration Number" %}
                </div>
                <div class="col-sm-6">
                  {% include 'form_field.html' with field=form.email label=form.email.label %}
                </div>
              </div>
              <div class="form-group row">
                <div class="col-sm-6 mb-3 mb-sm-0">
                  {% include 'form_field.html' with field=form.first_name label=form.first_name.label %}
                </div>
                <div class="col-sm-6">
                    {% include 'form_field.html' with field=form.last_name label=form.last_name.label %}
                </div>
              </div>

              {% if form.password1 %}
                <!-- available only in create view -->
                <div class="form-group row">
                  <div class="col-sm-6 mb-3 mb-sm-0">
                      {% include 'form_field.html' with field=form.password1 label=form.password1.label %}
                  </div>
                  <div class="col-sm-6">
                      {% include 'form_field.html' with field=form.password2 label=form.password2.label %}
                  </div>
                </div>
              {% endif %}

              <div class="col-xl-2 float-right">
                  <button class="btn btn-primary btn-user btn-block" type="submit">Salvar</button>
              </div>
              <div class="col-xl-2 float-right">
                  <a class="btn btn-secondary btn-user btn-block" href="{% url 'accounts:list-teacher' %}">Voltar</a>
              </div>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

{% block extra_scripts %}
  <script>
    $(function () {
      $("#id_cpf").addClass("placeholder-upper")
      $('label[for="id_cpf"]').addClass("text-uppercase")
    });
  </script>
{% endblock extra_scripts %}

frontend/templates/accounts/teacher/teacher_list.html
{% extends 'dashboard_base.html' %}
{% load static %}

{% block title %} Professores {% endblock title %}
{% block extra_styles %}
    <link href="{% static 'styles/list.css' %}" rel="stylesheet">
{% endblock extra_styles %}


{% block content %}
    <h1 class="h1 mb-2 text-gray-800">Professores</h1>
    <p class="mb-4">Lista de Professor vinculados a instituição {{ request.user.admin.institution }}<br>
      <a href="{% url 'accounts:create-teacher' %}">
        Clique aqui para adicionar
        <i class="fas fa-plus-circle"></i>
      </a><br>
      <a href="{% url 'core:dashboard'%}">
        <i class="fas fa-arrow-circle-left"></i>
        Voltar a pagina inicial
      </a>
    </p>

    <div class="card shadow mb-4">
      <div class="card-body">
        <div class="table-responsive">
          <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
            <thead>
              <tr>
                <th>Nome</th>
                <th>Ações</th>
              </tr>
            </thead>
            <tbody>
              {% for teacher in teachers %}  
                <tr>
                    <td><span class="font-weight-bold" data-teacher-id="{{ teacher.id }}"> {{ teacher.user.first_name }} {{ teacher.user.last_name }} - {{ teacher.user.email }}</span></td>
                    <td>
                      <a href="{% url 'accounts:update-teacher' pk=teacher.pk %}" class="btn btn-edit btn-warning btn-circle"
                        data-toggle="tooltip" data-placement="right" title="Editar Professor">
                        <i class="fas fa-edit"></i>
                      </a>
                      <a href="{% url 'accounts:delete-teacher' pk=teacher.user.pk %}" class="btn btn-danger btn-circle"
                        data-toggle="tooltip" data-placement="right" title="Excluir Professor">
                        <i class="fas fa-trash"></i>
                      </a>
                    </td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
{% endblock content %}

{% block extra_scripts %}
  <script src="{% static 'theme/vendor/datatables/jquery.dataTables.min.js' %}"></script>
  <script src="{% static 'theme/vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>
  <script src="{% static 'js/list.js' %}"></script>
{% endblock extra_scripts %}