class_path_web/accounts/api/urls.py
from django.urls import path

from . import viewsets


urlpatterns = [
    path('program-informations', viewsets.program_informations, name='program-informations'),
    path('class-informations', viewsets.class_informations, name='class-informations'),
]

class_path_web/accounts/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views

from . import views


urlpatterns = [
    path('api/', include(('class_path_web.accounts.api.urls', 'core'), namespace="core")),
    path('sign-up/', views.signup, name='sign-up'),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    path(
        'login/',
        auth_views.LoginView.as_view(
            template_name='accounts/login.html',
            redirect_authenticated_user=True
        ),
        name="login"
    ),
    # create
    path('create-program/', views.create_program, name='create-program'),
    path('create-teacher/', views.create_teacher, name='create-teacher'),
    path('create-class/<int:program>/', views.create_class, name='create-class'),
    path('create-student/<int:class>/', views.create_student, name='create-student'),
    path('create-course/<int:class>/', views.create_course, name='create-course'),
    path('create-address/', views.create_address, name='create_address'),
    # update
    path('update-program/<int:pk>/', views.update_program, name='update-program'),
    path('update-teacher/<int:pk>/', views.update_teacher, name='update-teacher'),
    path('update_class/<int:pk>/', views.update_class, name='update-class'),
    path('update-student/<int:pk>/', views.update_student, name='update-student'),
    path('update-course/<int:pk>/', views.update_course, name='update-course'),
    path('update-profile/', views.update_profile, name='update_profile'),
    path('update-address/<int:pk>/', views.update_address, name='update_address'),
    path(
        'define-scores/<int:student>/<int:course>/',
        views.define_scores,
        name='define-scores'
    ),
    # list
    path('programs/', views.list_program, name='list-program'),
    path('teachers/', views.list_teacher, name='list-teacher'),
    path('teacher-courses/', views.list_teacher_courses, name='list-teacher-courses'),
    path('classes/<int:program>/', views.list_class, name='list-class'),
    path('class/<int:course>/', views.list_class_students, name='list-class-students'),
    path('students/<int:class>/', views.list_student, name='list-student'),
    path('courses/<int:class>/', views.list_course, name='list-course'),
    # delete
    path('delete-program/<int:pk>/', views.delete_program, name='delete-program'),
    path('delete-class/<int:pk>/', views.delete_class, name='delete-class'),
    path('delete-teacher/<int:pk>/', views.delete_teacher, name='delete-teacher'),
    path('delete-student/<int:pk>/', views.delete_student, name='delete-student'),
    path('delete-course/<int:pk>/', views.delete_course, name='delete-course'),
    path('delete-address/<int:pk>/', views.delete_address, name='delete-address'),
    # detail
    path('profile/', views.profile_view, name='profile'),
    # has no institution urls
    path('teacher/sign-up/', views.sign_up_teacher, name='teacher-sign-up'),
    path('teacher/create-class/', views.create_teacher_class, name="teacher-create-class"),
    path('teacher/classes/', views.teacher_classes, name='teacher-classes'),
]

class_path_web/core/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('', views.home, name='home'),
    path('dashboard/', views.dashboard, name='dashboard'),
]

class_path_web/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include 


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('class_path_web.core.urls', 'core'), namespace="core")),
    path(
        'accounts/',
        include(
            ('class_path_web.accounts.urls', 'accounts'),
            namespace="accounts"
        )
    ),
    path(
        'location/',
        include(
            ('class_path_web.location.urls', 'location'),
            namespace="location"
        )
    ),
    path(
        'content/',
        include(
            ('class_path_web.content.urls', 'content'),
            namespace="content"
        )
    )
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

class_path_web/accounts/models.py
from django.contrib.auth.models import AbstractUser, Permission
from django.contrib.contenttypes.models import ContentType

from django.db import models

from django.utils.translation import gettext_lazy as _

from .managers import CustomUserManager


class User(AbstractUser):
    registration_number = models.CharField(
        _('registration number'),
        max_length=25,
        unique=True
    )
    email = models.EmailField(_('email address'), unique=True)
    is_teacher = models.BooleanField(_('is teacher'), default=False)
    is_student = models.BooleanField(_('is student'), default=False)
    is_admin = models.BooleanField(_('is admin'), default=False)
    has_institution = models.BooleanField(_('has institution'), default=True)

    objects = CustomUserManager()

    username = None

    USERNAME_FIELD = 'registration_number'

    class Meta:
        db_table = 'users'

    def __str__(self):
        return self.email


class Profile(models.Model):
    cpf = models.CharField(
        _('cpf'),
        max_length=100,
        default=None,
        null=True,
        blank=True
    )
    description = models.TextField(_('description'), blank=True, null=True)
    is_active = models.BooleanField(_('is active'), default=True)
    created_at = models.DateTimeField(_('created at'), auto_now_add=True)
    modified_at = models.DateTimeField(_('modified at'), auto_now=True)

    class Meta:
        abstract = True

    def __str__(self):
        return self.user.email


class Institution(models.Model):
    name = models.CharField(_('name'), max_length=250)
    description = models.TextField(_('description'), blank=True, null=True)
    created_at = models.DateTimeField(_('created at'), auto_now_add=True)
    modified_at = models.DateTimeField(_('modified at'), auto_now=True)

    class Meta:
        db_table = 'institution'

    def __str__(self):
        return self.name


class Program(models.Model):
    name = models.CharField(_('name'), max_length=200)
    description = models.TextField(_('description'), blank=True, null=True)
    institution = models.ForeignKey(
        Institution,
        related_name="programs",
        on_delete=models.CASCADE
    )
    created_at = models.DateTimeField(_('created at'), auto_now_add=True)
    modified_at = models.DateTimeField(_('modified at'), auto_now=True)

    class Meta:
        db_table = 'program'

    def __str__(self):
        return self.name


class Teacher(Profile):
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        related_name="teacher"
    )
    institution = models.ForeignKey(
        Institution,
        on_delete=models.CASCADE,
        related_name="teachers",
        null=True,
    )
    created_at = models.DateTimeField(_('created at'), auto_now_add=True)
    modified_at = models.DateTimeField(_('modified at'), auto_now=True)

    class Meta:
        db_table = 'teacher'


class Class(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(blank=True, null=True)
    program = models.ForeignKey(
        Program,
        on_delete=models.CASCADE,
        related_name="classes",
        null=True
    )
    teacher = models.ForeignKey(
        Teacher,
        on_delete=models.CASCADE,
        related_name="classes",
        null=True
    )
    created_at = models.DateTimeField(_('created at'), auto_now_add=True)
    modified_at = models.DateTimeField(_('modified at'), auto_now=True)

    class Meta:
        db_table = 'class'

    def __str__(self):
        return self.name


class Admin(Profile):
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        related_name="admin"
    )
    institution = models.ForeignKey(
        Institution,
        on_delete=models.CASCADE,
        related_name="admins",
        null=True,
    )
    created_at = models.DateTimeField(_('created at'), auto_now_add=True)
    modified_at = models.DateTimeField(_('modified at'), auto_now=True)

    class Meta:
        db_table = 'admin'


class Student(Profile):
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        related_name="student"
    )
    class_id = models.ForeignKey(
        Class,
        on_delete=models.CASCADE,
        related_name="students"
    )
    created_at = models.DateTimeField(_('created at'), auto_now_add=True)
    modified_at = models.DateTimeField(_('modified at'), auto_now=True)

    class Meta:
        db_table = 'student'


class Address(models.Model):
    state = models.CharField(_('state'), max_length=2)
    city = models.CharField(_('city'), max_length=100)
    street = models.CharField(_('street'), max_length=250)
    neighborhood = models.CharField(_('neighborhood'), max_length=100)
    number = models.IntegerField(_('number'), null=True)
    postal_code = models.CharField(_('postal code'), max_length=250)
    complement = models.CharField(
        _('complement'),
        max_length=250,
        blank=True,
        null=True
    )
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='addresses'
    )
    created_at = models.DateTimeField(_('created at'), auto_now_add=True)
    modified_at = models.DateTimeField(_('modified at'), auto_now=True)

    class Meta:
        db_table = 'address'

    def __str__(self):
       return f'{self.street} {self.number}, {self.postal_code}'


class Course(models.Model):
    name = models.CharField(_('name'), max_length=200)
    description = models.TextField(_('description'), blank=True, null=True)
    class_id = models.ForeignKey(
        Class,
        on_delete=models.CASCADE,
        related_name="courses"
    )
    teacher = models.ForeignKey(
        Teacher,
        on_delete=models.CASCADE,
        related_name="courses"
    )
    created_at = models.DateTimeField(_('created at'), auto_now_add=True)
    modified_at = models.DateTimeField(_('modified at'), auto_now=True)

    class Meta:
        db_table = 'course'

    def __str__(self):
        return self.name


class Scores(models.Model):
    first_score = models.FloatField(_('first score'), null=True)
    second_score = models.FloatField(_('second score'), null=True)
    third_score = models.FloatField(_('third score'), null=True)
    student = models.ForeignKey(
        Student,
        on_delete=models.CASCADE,
        related_name="scores"
    )
    course = models.ForeignKey(
        Course,
        on_delete=models.CASCADE,
        related_name="scores"
    )
    created_at = models.DateTimeField(_('created at'), auto_now_add=True)
    modified_at = models.DateTimeField(_('modified at'), auto_now=True)

    class Meta:
        db_table = 'scores'

    def __str__(self):
        return self.name

class_path_web/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm

from . import models


class InstitutionForm(ModelForm):
    class Meta:
        model = models.Institution
        fields = (
            'name', 'description',
        )


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = models.User
        fields = (
            "registration_number", "email",
            "first_name", "last_name",
        )

    def process_cleaned_data(self):
        data = self.cleaned_data.copy()

        del data['password2']

        data['password'] = data.pop('password1')
        return data

    def save(self):
        # define user permission field
        data = self.process_cleaned_data()
        # create user
        user = models.User.objects.create_user(**data)
        return user


class CustomUserUpdateForm(ModelForm):
    class Meta:
        model = models.User
        fields = (
            "registration_number", "email",
            "first_name", "last_name",
        )


class ProfileForm(ModelForm):
    class Meta:
        model = models.Teacher
        fields = (
            'cpf', 'description',
        )


class AddressForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['number'].required = False

    class Meta:
        model = models.Address
        fields = (
            'state', 'city', 'street',
            'neighborhood', 'number',
            'postal_code', 'complement'
        )


class ProgramForm(ModelForm):
    class Meta:
        model = models.Program
        fields = (
            'name', 'description'
        )


class ClassForm(ModelForm):
    class Meta:
        model = models.Class
        fields = (
            'name', 'description'
        )


class CourseForm(ModelForm):
    class Meta:
        model = models.Course
        fields = (
            'name', 'description',
            'teacher'
        )


class ScoreForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['first_score'].required = False
        self.fields['second_score'].required = False
        self.fields['third_score'].required = False

    class Meta:
        model = models.Scores
        fields = (
            'first_score', 'second_score',
            'third_score',
        )

frontend/templates/accounts/login.html
{% extends "base_offline.html" %}
{% load widget_tweaks %}
{% load static %}

{% block title %} Login {% endblock title %}

{% block content %}
    <div class="row justify-content-center">
        <div class="col-xl-10 col-lg-12 col-md-9">
            <div class="card o-hidden border-0 shadow-lg my-5">
                <div class="card-body p-0">
                    <!-- Nested Row within Card Body -->
                    <div class="row">
                        <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
                        <div class="col-lg-6">
                            <div class="p-5">
                                <div class="text-center">
                                    <h1 class="h4 text-gray-900 mb-4">Entrar</h1>
                                </div>
                                <form class="user" action="" method="POST">
                                    {% csrf_token %}
                                    {{ form.non_field_errors }}
                                    <div class="form-group">
                                        {% render_field form.username class="form-control form-control-user" placeholder="Numero de Matricula" %}
                                    </div>
                                    <div class="form-group">
                                        {% render_field form.password class="form-control form-control-user" placeholder="Senha" %}
                                    </div>
                                    <!-- <div class="form-group">
                                        <div class="custom-control custom-checkbox small">
                                            <input type="checkbox" class="custom-control-input" id="customCheck">
                                            <label class="custom-control-label" for="customCheck">Remember Me</label>
                                        </div>
                                    </div> -->
                                    <button class="btn btn-primary btn-user btn-block" type="submit">Entrar</button>
                                </form>
                                <hr>
                                <div class="text-center">
                                    <a class="small" href="{% url 'accounts:sign-up' %}">Criar conta
                                </div>
                                <div class="text-center">
                                    <a class="small" href="#">Esqueci minha senha</a>
                                </div>
                                <div class="text-center">
                                    <a class="small" href="{% url 'core:home' %}">Voltar a Pagina Inicial</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

frontend/templates/accounts/profile.html
{% extends 'dashboard_base.html' %}
{% load static %}

{% block title %}
  Perfil
{% endblock %}

{% block content %}

<div>
    <img class="profile-foto" src="{% static 'media/profile.png' %}">
    <p>
        <h5>
            <i class="fas fa-edit"></i>
            <a href="{% url 'accounts:update_profile' %}">Editar Perfil</a>
        </h5>
    </p>
    {% if profile.user.registration_number %}
        <p class="mb-4"><strong>Username / Numero de Matricula:</strong> {{ profile.user.registration_number }}</p>
    {% endif %}

    {% if profile.user.first_name  %}
        <p class="mb-4"><strong>Nome:</strong> {{ profile.user.first_name  }}</p>
    {% endif %}

    {% if profile.user.last_name %}
        <p class="mb-4"><strong>Sobrenome:</strong> {{ profile.user.last_name }}</p>
    {% endif %}

    {% if profile.cpf %}
        <p class="mb-4"><strong>CPF:</strong> {{ profile.cpf|upper }}</p>
    {% endif %}

    {% if profile.description %}
        <p class="mb-4"><strong>Biografia:</strong> {{ profile.description }}</p>
    {% endif %}

    <hr>

    {% with user.addresses.all as addresses %}
        {% if addresses %}
            <h4> Endereços </h5>
            <p>
                <h5>
                    <i class="fas fa-plus-circle"></i>
                    <a href="{% url 'accounts:create_address' %}">Adicionar um novo Endereço</a>
                </h5>
            </p>

            <div class="row justify-content-left">
                {% for address in addresses %}
                    <div class="col-xl-4 col-md-6 mb-4">
                        <div class="card border-left-warning home-cards shadow h-200 py-3">
                            <div class="card-body">
                            <div class="row no-gutters align-items-center">
                                <div class="col mr-2">
                                    <div class="font-weight-bold mb-1">
                                        <p>Street: {{ address.street }}</p>
                                        <p>Number: {{ address.number|default_if_none:"S/N" }}</p>
                                        <p>Neighborhood: {{ address.neighborhood }}</p>
                                        {% if address.complement %}
                                            <p>Complement: {{ address.complement }}</p>
                                        {% endif %}
                                        <p>City: {{ address.city }}</p>
                                        <p>State: {{ address.state }}</p>
                                        <p>Postal Code: {{ address.postal_code }}</p>
                                        <p>
                                          <a href="{% url 'accounts:update_address' pk=address.id %}">
                                            <i class="fas fa-edit edit"></i>
                                            Editar
                                          </a>
                                        </p>
                                        <p>
                                          <a href="{% url 'accounts:delete-address' pk=address.id %}">
                                              <i class="fas fa-trash trash"></i>
                                              Excluir
                                          </a>
                                        </p>
                                    </div>
                                </div>
                            </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% else %}
            <p>
                <h5>
                    <i class="fas fa-plus-circle"></i>
                    <a href="{% url 'accounts:create_address' %}">Adicionar Endereço</a>
                </h5>
            </p>
        {% endif %}
    {% endwith %}
</div>

{% endblock content %}

frontend/templates/accounts/profile_form.html
{% extends 'dashboard_base.html' %}
{% load staticfiles %}

{% block title %} Editar Perfil {% endblock title %}

{% block extra_styles %}
    <link href="{% static 'styles/form.css' %}" rel="stylesheet">
{% endblock extra_styles %}

{% block content %}
<h1 class="h3 mb-2 text-gray-800">Editar Perfil</h1>
<p class="mb-4">Edite seus dados de perfil.</p>
<div class="col-xl-10 col-lg-10">
    <div class="card shadow mb-4 border-left-primary">
        <div class="card-body">
            <form action="" method="POST">

              {% csrf_token %}

              {% if profile_form %}
                <!-- available only in update view -->
                <div class="form-group">
                  {% include 'form_field.html' with field=profile_form.cpf label=profile_form.cpf.label %}
                </div>
                <div class="form-group">
                  {% include 'form_field.html' with field=profile_form.description label=profile_form.description.label %}
                </div>
              {% endif %}

              <div class="form-group row">
                <div class="col-sm-6 mb-3 mb-sm-0">
                  {% include 'form_field.html' with field=form.registration_number label="Username / Registration Number" %}
                </div>
                <div class="col-sm-6">
                  {% include 'form_field.html' with field=form.email label=form.email.label %}
                </div>
              </div>
              <div class="form-group row">
                <div class="col-sm-6 mb-3 mb-sm-0">
                  {% include 'form_field.html' with field=form.first_name label=form.first_name.label %}
                </div>
                <div class="col-sm-6">
                    {% include 'form_field.html' with field=form.last_name label=form.last_name.label %}
                </div>
              </div>

              {% if form.password1 %}
                <!-- available only in create view -->
                <div class="form-group row">
                  <div class="col-sm-6 mb-3 mb-sm-0">
                      {% include 'form_field.html' with field=form.password1 label=form.password1.label %}
                  </div>
                  <div class="col-sm-6">
                      {% include 'form_field.html' with field=form.password2 label=form.password2.label %}
                  </div>
                </div>
              {% endif %}

              <div class="col-xl-2 float-right">
                  <button class="btn btn-primary btn-user btn-block" type="submit">Salvar</button>
              </div>
              <div class="col-xl-2 float-right">
                  <a class="btn btn-secondary btn-user btn-block" href="#">Voltar</a>
              </div>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

{% block extra_scripts %}
  <script>
    $(function () {
      $("#id_cpf").addClass("placeholder-upper")
      $('label[for="id_cpf"]').addClass("text-uppercase")
    });
  </script>
{% endblock extra_scripts %}

frontend/templates/accounts/signup.html
{% extends "base_offline.html" %}
{% load widget_tweaks %}
{% load static %}

{% block styles %}
  <link href="{% static 'styles/signup.css' %}" rel="stylesheet">
{% endblock %}


{% block title %} Sign Up {% endblock title %}


{% block content %}
  <div class="card o-hidden border-0 shadow-lg my-5">
    <div class="card-body p-0">
      <div class="row">
        <div class="col-lg-5 d-none d-lg-block bg-register-image"></div>
        <div class="col-lg-7">
          <div class="p-5">
            <div class="text-center">
              <h1 class="h4 text-gray-900 mb-4">Junte-se a nós!</h1>
            </div>
            <form action="" method="POST">
              {% csrf_token %}

              {% if institution_form %}
                <div class="text-center form-header">
                  <h4>Informações da Instituição</h4>
                </div>
                <div class="form-group">
                  {% if institution_form.name.errors %}
                    {% render_field institution_form.name class="form-control form-control-user is-invalid" placeholder=institution_form.name.label %}
                    {{ institution_form.name.errors|striptags }}
                  {% else %}
                    {% render_field institution_form.name class="form-control form-control-user" placeholder=institution_form.name.label %}
                  {% endif %}
                </div>
                <div class="form-group">
                  {% if institution_form.description.errors %}
                    {% render_field institution_form.description class="form-control is-invalid" placeholder=institution_form.description.label %}
                    {{ institution_form.description.errors|striptags }}
                  {% else %}
                    {% render_field institution_form.description class="form-control" placeholder=institution_form.description.label %}
                  {% endif %}
                </div>
              {% endif %}

              <div class="text-center form-header">
                <h4>Informações do Usuário</h4>
              </div>
              <div class="form-group row">
                <div class="col-sm-6 mb-3 mb-sm-0">
                  {% if user_form.registration_number.errors %}
                    {% render_field user_form.registration_number class="form-control form-control-user is-invalid" placeholder=user_form.registration_number.label %}
                    {{ user_form.registration_number.errors|striptags }}
                  {% else %}
                    {% render_field user_form.registration_number class="form-control form-control-user" placeholder=user_form.registration_number.label %}
                  {% endif %}
                </div>
                <div class="col-sm-6">
                  {% if user_form.email.errors %}
                    {% render_field user_form.email class="form-control form-control-user is-invalid" placeholder=user_form.email.label %}
                    {{ user_form.email.errors|striptags }}
                  {% else %}
                    {% render_field user_form.email class="form-control form-control-user" placeholder=user_form.email.label %}
                  {% endif %}
                </div>
              </div>
              <div class="form-group row">
                <div class="col-sm-6 mb-3 mb-sm-0">
                  {% if user_form.first_name.errors %}
                    {% render_field user_form.first_name class="form-control form-control-user is-invalid" placeholder=user_form.first_name.label %}
                    {{ user_form.first_name.errors|striptags }}
                  {% else %}
                    {% render_field user_form.first_name class="form-control form-control-user" placeholder=user_form.first_name.label %}
                  {% endif %}
                </div>
                <div class="col-sm-6">
                  {% if user_form.last_name.errors %}
                    {% render_field user_form.last_name class="form-control form-control-user is-invalid" placeholder=user_form.last_name.label %}
                    {{ user_form.last_name.errors|striptags }}
                  {% else %}
                    {% render_field user_form.last_name class="form-control form-control-user" placeholder=user_form.last_name.label %}
                  {% endif %}
                </div>
              </div>
              <div class="form-group row">
                <div class="col-sm-6 mb-3 mb-sm-0">
                  {% if user_form.password1.errors %}
                    {% render_field user_form.password1 class="form-control form-control-user is-invalid" placeholder=user_form.password1.label %}
                    {{ user_form.password1.errors|striptags }}
                  {% else %}
                    {% render_field user_form.password1 class="form-control form-control-user" placeholder=user_form.password1.label %}
                  {% endif %}
                </div>
                <div class="col-sm-6">
                  {% if user_form.password2.errors %}
                    {% render_field user_form.password2 class="form-control form-control-user is-invalid" placeholder=user_form.password2.label %}
                    {{ user_form.password2.errors|striptags }}
                  {% else %}
                    {% render_field user_form.password2 class="form-control form-control-user" placeholder=user_form.password2.label %}
                  {% endif %}
                </div>
              </div>
              <button class="btn btn-primary btn-user btn-block" type="submit">
                Criar
              </button>
            </form>
            <hr>
            <div class="text-center">
              <a class="small" href="{% url 'accounts:login' %}">Ir para tela de Login</a>
            </div>
            <div class="text-center">
              <a class="small" href="{% url 'core:home' %}">Voltar a Pagina Inicial</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}