class_path_web/accounts/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views

from . import views


urlpatterns = [
    path('api/', include(('class_path_web.accounts.api.urls', 'core'), namespace="core")),
    path('sign-up/', views.signup, name='sign-up'),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    path(
        'login/',
        auth_views.LoginView.as_view(
            template_name='accounts/login.html',
            redirect_authenticated_user=True
        ),
        name="login"
    ),
    # create
    path('create-program/', views.create_program, name='create-program'),
    path('create-teacher/', views.create_teacher, name='create-teacher'),
    path('create-class/<int:program>/', views.create_class, name='create-class'),
    path('create-student/<int:class>/', views.create_student, name='create-student'),
    path('create-course/<int:class>/', views.create_course, name='create-course'),
    path('create-address/', views.create_address, name='create_address'),
    # update
    path('update-program/<int:pk>/', views.update_program, name='update-program'),
    path('update-teacher/<int:pk>/', views.update_teacher, name='update-teacher'),
    path('update_class/<int:pk>/', views.update_class, name='update-class'),
    path('update-student/<int:pk>/', views.update_student, name='update-student'),
    path('update-course/<int:pk>/', views.update_course, name='update-course'),
    path('update-profile/', views.update_profile, name='update_profile'),
    path('update-address/<int:pk>/', views.update_address, name='update_address'),
    path(
        'define-scores/<int:student>/<int:course>/',
        views.define_scores,
        name='define-scores'
    ),
    # list
    path('programs/', views.list_program, name='list-program'),
    path('teachers/', views.list_teacher, name='list-teacher'),
    path('teacher-courses/', views.list_teacher_courses, name='list-teacher-courses'),
    path('classes/<int:program>/', views.list_class, name='list-class'),
    path('class/<int:course>/', views.list_class_students, name='list-class-students'),
    path('students/<int:class>/', views.list_student, name='list-student'),
    path('courses/<int:class>/', views.list_course, name='list-course'),
    # delete
    path('delete-program/<int:pk>/', views.delete_program, name='delete-program'),
    path('delete-class/<int:pk>/', views.delete_class, name='delete-class'),
    path('delete-teacher/<int:pk>/', views.delete_teacher, name='delete-teacher'),
    path('delete-student/<int:pk>/', views.delete_student, name='delete-student'),
    path('delete-course/<int:pk>/', views.delete_course, name='delete-course'),
    path('delete-address/<int:pk>/', views.delete_address, name='delete-address'),
    # detail
    path('profile/', views.profile_view, name='profile'),
    # has no institution urls
    path('teacher/sign-up/', views.sign_up_teacher, name='teacher-sign-up'),
    path('teacher/create-class/', views.create_teacher_class, name="teacher-create-class"),
    path('teacher/classes/', views.teacher_classes, name='teacher-classes'),
]

class_path_web/content/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('create-content/', views.create_content, name='create-content'),
    path('create-activity/', views.create_activity, name='create-activity'),
    path('update-content/<int:pk>/', views.update_content, name='update-content'),
    path('update-activity/<int:pk>/', views.update_activity, name='update-activity'),
    path('delete-content/<int:pk>/', views.delete_content, name='delete-content'),
    path('delete-activity/<int:pk>/', views.delete_activity, name='delete-activity'),
    path('list-content/', views.list_content, name='list-content'),
    path('list-activity/', views.list_activity, name='list-activity')
]

class_path_web/core/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('', views.home, name='home'),
    path('dashboard/', views.dashboard, name='dashboard'),
]

class_path_web/location/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('create-location/', views.create_location, name='create-location'),
    path('update-location/<int:pk>/', views.update_location, name='update-location'),
    path('delete-location/<int:pk>/', views.delete_location, name='delete-location'),
    path('list-location/', views.list_location, name='list-location'),
]

class_path_web/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include 


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('class_path_web.core.urls', 'core'), namespace="core")),
    path(
        'accounts/',
        include(
            ('class_path_web.accounts.urls', 'accounts'),
            namespace="accounts"
        )
    ),
    path(
        'location/',
        include(
            ('class_path_web.location.urls', 'location'),
            namespace="location"
        )
    ),
    path(
        'content/',
        include(
            ('class_path_web.content.urls', 'content'),
            namespace="content"
        )
    )
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

frontend/templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Class Path | {% block title %} {% endblock title%}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="{% static 'styles/main.css' %}" rel="stylesheet">
    {% block extra_css %}{% endblock extra_css %}

  </head>
  <body class="text-center">

    <div class="cover-container d-flex h-100 p-3 mx-auto flex-column">
        {% block content %}
        {% endblock content %}

      <footer class="mastfoot mt-auto">
        <div class="inner">
            © <a href="https://github.com/werberth">Betim</a> – Built with Django 2 and Bootstrap 4
        </div>
      </footer>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static 'theme/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    {% block scripts %} {% endblock scripts %}
  </body>
</html>

frontend/templates/base_offline.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>ClassPath | {% block title %} {% endblock title %}</title>

  <!-- Custom fonts for this template-->
  <link href="{% static 'theme/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="{% static 'theme/css/sb-admin-2.min.css' %}" rel="stylesheet">
  {% block styles %}
  {% endblock %}

</head>

<body class="bg-gradient-primary">

  <div class="container">
    {% block content %}
    {% endblock %}
  </div>

  <!-- Bootstrap core JavaScript-->
  <script src="{% static 'theme/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'theme/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{% static 'theme/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{% static 'theme/js/sb-admin-2.min.js' %}"></script>
  {% block scripts %} {% endblock scripts %}
</body>

</html>

frontend/templates/dashboard_base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Class Path Dashboard | {% block title %}  {% endblock title %}</title>

  <link href="{% static 'theme/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <link href="{% static 'theme/css/sb-admin-2.min.css' %}" rel="stylesheet">
  <link href="{% static 'styles/main.css' %}" rel="stylesheet">
  {% block extra_styles %}
  {% endblock extra_styles %}

</head>

<body id="page-top">
  <div id="wrapper">
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
      <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'core:dashboard' %}">
        <div class="sidebar-brand-icon home-page-brand">
            <img src="{% static 'media/icon.png' %}">
        </div>
        <div class="sidebar-brand-text mx-3">Class Path</div>
      </a>

      <hr class="sidebar-divider my-0">

      {% if perms.accounts.is_admin %}

        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:list-program' %}">
              <i class="fas fa-fw fa-graduation-cap"></i>
            <span>Cursos</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:list-teacher' %}">
            <i class="fas fa-chalkboard-teacher"></i>
            <span>Professores</span></a>
        </li>

      {% elif perms.accounts.is_teacher %}
        <li class="nav-item">
          {% if perms.accounts.has_no_institution %}
            <a class="nav-link" href="{% url 'accounts:teacher-classes' %}">
              <i class="fas fa-fw fa-graduation-cap"></i>
              <span>Turmas</span>
            </a>
          {% else %}
            <a class="nav-link" href="{% url 'accounts:list-teacher-courses' %}">
              <i class="fas fa-chalkboard"></i>
              <span>Disciplinas</span>
            </a>
          {% endif %}
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'location:list-location' %}">
            <i class="fas fa-map-marked-alt"></i>
            <span>Localizações</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'content:list-content' %}">
              <i class="fas fa-bookmark"></i>
              <span>Conteúdos</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'content:list-activity' %}">
              <i class="fas fa-tasks"></i>
              <span>Atividades</span></a>
        </li>
      {% endif %}

      <hr class="sidebar-divider d-none d-md-block">

      <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
      </div>
    </ul>
    <div id="content-wrapper" class="d-flex flex-column">
      <div id="content">
        <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
          <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
            <i class="fa fa-bars"></i>
          </button>
          
          <ul class="navbar-nav ml-auto">
            <li class="nav-item dropdown no-arrow">

              <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ request.user.email }}</span>
                <i class="img-profile fas fa-user-circle fa-2x"></i>
              </a>

              <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                <a class="dropdown-item" href="{% url 'accounts:profile' %}">
                  <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                  Profile
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'accounts:logout' %}">
                  <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                  Logout
                </a>
              </div>
            </li>
          </ul>
        </nav>

        <div class="container-fluid">
            {% block content %}
            {% endblock content %}
        </div>

      </div>
      <footer class="sticky-footer bg-white">
        <div class="container my-auto">
          <div class="copyright text-center my-auto">
            <span>© <a href="https://github.com/werberth">Betim</a> – Built with Django 2 and Bootstrap 4</span>
          </div>
        </div>
      </footer>
    </div>

  </div>

  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>

  <script src="{% static 'theme/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'theme/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <script src="{% static 'theme/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <script src="{% static 'theme/js/sb-admin-2.min.js' %}"></script>
  {% block extra_scripts %}
  {% endblock extra_scripts %}
</body>

</html>

frontend/templates/dashboard_home.html
{% extends 'dashboard_base.html' %}
{% load staticfiles %}

{% block title %} Home {% endblock title %}
{% block extra_styles %}
    <link href="{% static 'styles/dashboard_home.css' %}" rel="stylesheet">
{% endblock extra_styles %}

{% block content %}
{% if perms.accounts.is_admin %}
<div class="row justify-content-center">
  <div class="col-xl-4 col-md-6 mb-4">
    <div class="card border-left-primary home-cards shadow h-100 py-3">
      <div class="card-body">
        <div class="row no-gutters align-items-center">
          <div class="col mr-2">
            <div class="text-md-center font-weight-bold text-primary text-uppercase mb-1">
              <a class="stretched-link"  href="{% url 'accounts:list-program' %}">
                Cursos
                <i class="fas fa-fw fa-graduation-cap fa-2x text-primary"></i>
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="col-xl-4 col-md-6 mb-4">
    <div class="card border-left-info home-cards shadow h-200 py-3">
      <div class="card-body">
        <div class="row no-gutters align-items-center">
          <div class="col mr-2">
            <div class="text-md-center font-weight-bold text-primary text-uppercase mb-1">
                <a class="stretched-link" href="{% url 'accounts:list-teacher' %}">
                  Professores
                  <i class="fas fa-chalkboard-teacher fa-2x text-primary"></i>
                </a>
              </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% elif perms.accounts.is_teacher %}
<div class="row justify-content-center">
  <div class="col-xl-4 col-md-6 mb-4">
    <div class="card border-left-primary home-cards shadow h-100 py-3">
      <div class="card-body">
        <div class="row no-gutters align-items-center">
          <div class="col mr-2">
            <div class="text-md-center font-weight-bold text-primary text-uppercase mb-1">
              {% if perms.accounts.has_no_institution %}
                <a class="stretched-link"  href="{% url 'accounts:teacher-classes' %}">
                  Turmas
                  <i class="fas fa-fw fa-graduation-cap fa-2x text-primary"></i>
                </a>
              {% else %}
                <a class="stretched-link"  href="{% url 'accounts:list-teacher-courses' %}">
                    Disciplinas
                  <i class="fas fa-fw fa-chalkboard fa-2x text-primary"></i>
                </a>
              {% endif %}
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="col-xl-4 col-md-6 mb-4">
    <div class="card border-left-info home-cards shadow h-200 py-3">
      <div class="card-body">
        <div class="row no-gutters align-items-center">
          <div class="col mr-2">
            <div class="text-md-center font-weight-bold text-primary text-uppercase mb-1">
                <a class="stretched-link" href="{% url 'location:list-location' %}">
                  Localizações
                  <i class="fas fa-map-marked-alt fa-2x text-primary"></i>
                </a>
              </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="row justify-content-center">
    <div class="col-xl-4 col-md-6 mb-4">
      <div class="card border-left-primary home-cards shadow h-100 py-3">
        <div class="card-body">
          <div class="row no-gutters align-items-center">
            <div class="col mr-2">
              <div class="text-md-center font-weight-bold text-primary text-uppercase mb-1">
                <a class="stretched-link"  href="{% url 'content:list-content' %}">
                  Conteúdos
                  <i class="fas fa-bookmark fa-2x text-primary"></i>
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="col-xl-4 col-md-6 mb-4">
      <div class="card border-left-info home-cards shadow h-200 py-3">
        <div class="card-body">
          <div class="row no-gutters align-items-center">
            <div class="col mr-2">
              <div class="text-md-center font-weight-bold text-primary text-uppercase mb-1">
                  <a class="stretched-link" href="{% url 'content:list-activity' %}">
                      Atividades
                    <i class="fas fa-tasks fa-2x text-primary"></i>
                  </a>
                </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endif %}
{% endblock %}

frontend/templates/form_field.html
{% load widget_tweaks %}

<label for="{{ field.auto_id }}">
    {% if label %}
        {{ label }}:
    {% else %}
        {{ field.label }}:
    {% endif %}
</label>

{% if field.errors %}
    {% render_field field class="form-control is-invalid" %}
    {{ field.errors|striptags }}
{% else %}
    {% render_field field class="form-control" %}
{% endif %}

frontend/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Home {% endblock title%}

{% block extra_css %}
  <link href="{% static 'styles/home.css' %}" rel="stylesheet">
{% endblock extra_css %}

{% block content %}
  <header class="home-page-header mb-auto">
    <div class="inner">
      <h4 class="home-page-brand">
        <img src="{% static 'media/icon.png' %}">
        <span>Class Path</span>
      </h3>
      <nav class="nav home-page-nav justify-content-center">
        <a class="nav-link active" href="{% url 'accounts:login' %}">Login</a>
      </nav>
    </div>
  </header>

  <main role="main" class="inner cover">
    <h2 class="cover-heading">Registre-se</h2>
    <p>Com o Class Path é muito fácil gerenciar uma instituição de ensino, suas turmas, disciplinas e criar conteúdos sensíveis ao contexto.</p>
    <p>
      <a href="{% url 'accounts:sign-up' %}" class="btn btn-lg btn-secondary">Criar Instituição</a>
      <a href="{% url 'accounts:teacher-sign-up' %}" class="btn btn-lg btn-secondary">Registre-se como Professor</a>
    </p>
  </main>
{% endblock content %}